### ISSUE TITLE
Handling dependencies

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/shareable-timelines-draft#1]
Running `npm run build` with the current configuration will bundle some bits of `jspsych` and some bits of `@jspsych/plugin-html-keyboard-response` in the dist file. This seems like it could create conflicts when people add a timeline and add the plugin in their experiment JS if using the browser version instead of node. I'm not sure what the standard solution is to this.

@bjoluc any chance you could point me in the right direction?

**Comment by bjoluc** [comment]
This project seems like a very useful idea!

Re bundling: esbuild is a great choice. I would recommend using the wonderful esbuild (and Rollup) wrapper [tsup](https://github.com/egoist/tsup) though: It allows to create an esm, iife, and types bundle in one run with sensible defaults.

> Running `npm run build` with the current configuration will bundle some bits of `jspsych` and some bits of `@jspsych/plugin-html-keyboard-response` in the dist file.

`JsPsych` is only used as a type in `index.ts` and `@jspsych/plugin-html-keyboard-response`, so not much of it is included. `ParameterType` is the only thing from `jspsych` that's really needed in the bundle. There are also a few false negatives from esbuild's treeshaking. Rollup does a better job at this and `tsup` has an option to let Rollup treeshake the bundle.

> This seems like it could create conflicts when people add a timeline and add the plugin in their experiment JS if using the browser version instead of node.

All dependencies are included in the IIFE build and none of our global `jsPsychXY` variables are used, so there should be no conflicts :+1: Bundling dependencies (at least for IIFE) makes perfect sense so the shared timelines are guaranteed to use proper plugin versions.

I'll submit a PR for a build setup using tsup.

**Comment by jodeleeuw** [comment]
Thanks for the explainer, this is super helpful. I'll move ahead with this setup and hope that I can sort out any remaining wrinkles on my own.
